### ISSUE TITLE
Correction of the robot mesh

### ISSUE THREAD

**Issue by Aljeune** [TakahanoParis/Takahano-Paris#11]
Robot has weird normals, 
Apply all modifiers and recalculate normal on blender could solve the problem

**Comment by Aljeune** [comment]
Yuchen, have you finished to rework the mesh ?

**Comment by Y-Seagle** [comment]
The newest version is RobotArm_FixedNorUVShading.FBX. every error should be fixed, please let me know if it's all okay

**Comment by Aljeune** [comment]
perfect, ty

**Comment by Aljeune** [comment]
Normal is... normal right now :)
